server:
  port: 8080

loadbalancer:
  algorithm: round-robin
  servers:
    - url: http://localhost:8081
      healthy: true
    - url: http://localhost:8082
      healthy: true
    - url: http://localhost:8083
      healthy: true

  health-check:
    path: /health
    interval-seconds: 30
    timeout-seconds: 5
    max-failures: 3
    success-threshold: 2

logging:
  level:
    com.liftlab.loadbalancer: DEBUG
    org.springframework: INFO